prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/lov_estado.sql
@@application/shared_components/navigation/lists/menú_de_navegación_de_escritorio.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/lista_acceso_directo.sql
@@application/shared_components/navigation/lists/lista_procesos.sql
@@application/shared_components/navigation/lists/lista_reportes_auditoria.sql
@@application/shared_components/navigation/lists/lista_plan_integral.sql
@@application/shared_components/files/expand_menu_js.sql
@@application/shared_components/files/utils_socios_js.sql
@@application/shared_components/files/utils_generico_js.sql
@@application/shared_components/files/style_coomecipar_css.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/logo_coomecipar_png.sql
@@application/shared_components/files/coomecipar_day_jpg.sql
@@application/shared_components/files/coomecipar_night_jpg.sql
@@application/shared_components/files/coomecipar_day_png.sql
@@application/shared_components/files/utils_js.sql
@@application/shared_components/files/audl0005_xlsx.sql
@@application/shared_components/files/audl0006_xlsx.sql
@@application/shared_components/files/audl0007_xlsx.sql
@@application/shared_components/files/jquery_mask_min_js.sql
@@application/shared_components/files/utils_auditoria_js.sql
@@application/shared_components/files/audl0004_xlsx.sql
@@application/shared_components/files/filomeni_jpeg.sql
@@application/shared_components/files/jquery_tabbable_min_js.sql
@@application/shared_components/files/audl0006_xlsm.sql
@@application/shared_components/files/audl0003unico_xlsx.sql
@@application/shared_components/files/audl0004_1_xlsx.sql
@@application/shared_components/files/audl0005_pdf.sql
@@application/shared_components/files/seguimiento_21122020_xlsx.sql
@@application/shared_components/files/inputmask_4_x_editorconfig.sql
@@application/shared_components/files/inputmask_4_x_eslintrc.sql
@@application/shared_components/files/inputmask_4_x_gitattributes.sql
@@application/shared_components/files/inputmask_4_x_github_issue_template_bug_report_md.sql
@@application/shared_components/files/inputmask_4_x_github_issue_template_feature_request_md.sql
@@application/shared_components/files/inputmask_4_x_gitignore.sql
@@application/shared_components/files/inputmask_4_x_changelog_md.sql
@@application/shared_components/files/inputmask_4_x_gruntfile_js.sql
@@application/shared_components/files/inputmask_4_x_license_txt.sql
@@application/shared_components/files/inputmask_4_x_readme_md.sql
@@application/shared_components/files/inputmask_4_x_readme_android_md.sql
@@application/shared_components/files/inputmask_4_x_readme_date_md.sql
@@application/shared_components/files/inputmask_4_x_readme_numeric_md.sql
@@application/shared_components/files/inputmask_4_x_readme_other_md.sql
@@application/shared_components/files/inputmask_4_x_bower_json.sql
@@application/shared_components/files/inputmask_4_x_bundle_js.sql
@@application/shared_components/files/inputmask_4_x_composer_json.sql
@@application/shared_components/files/inputmask_4_x_css_inputmask_css.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_bindings_inputmask_binding_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_dependencylibs_inputmask_dependencylib_jqlite_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_dependencylibs_inputmask_dependencylib_jquery_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_dependencylibs_inputmask_dependencylib_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_global_window_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_inputmask_date_extensions_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_inputmask_extensions_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_inputmask_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_inputmask_numeric_extensions_js.sql
@@application/shared_components/files/inputmask_4_x_dist_inputmask_jquery_inputmask_js.sql
@@application/shared_components/files/inputmask_4_x_dist_jquery_inputmask_bundle_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_bindings_inputmask_binding_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_dependencylibs_inputmask_dependencylib_jqlite_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_dependencylibs_inputmask_dependencylib_jquery_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_dependencylibs_inputmask_dependencylib_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_global_window_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_inputmask_date_extensions_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_inputmask_extensions_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_inputmask_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_inputmask_numeric_extensions_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_inputmask_jquery_inputmask_min_js.sql
@@application/shared_components/files/inputmask_4_x_dist_min_jquery_inputmask_bundle_min_js.sql
@@application/shared_components/files/inputmask_4_x_index_html.sql
@@application/shared_components/files/inputmask_4_x_index_js.sql
@@application/shared_components/files/inputmask_4_x_js_bindings_inputmask_binding_js.sql
@@application/shared_components/files/inputmask_4_x_js_dependencylibs_inputmask_dependencylib_jqlite_js.sql
@@application/shared_components/files/inputmask_4_x_js_dependencylibs_inputmask_dependencylib_jquery_js.sql
@@application/shared_components/files/inputmask_4_x_js_dependencylibs_inputmask_dependencylib_js.sql
@@application/shared_components/files/inputmask_4_x_js_global_window_js.sql
@@application/shared_components/files/inputmask_4_x_js_inputmask_date_extensions_js.sql
@@application/shared_components/files/inputmask_4_x_js_inputmask_extensions_js.sql
@@application/shared_components/files/inputmask_4_x_js_inputmask_js.sql
@@application/shared_components/files/inputmask_4_x_js_inputmask_numeric_extensions_js.sql
@@application/shared_components/files/inputmask_4_x_js_jquery_inputmask_js.sql
@@application/shared_components/files/inputmask_4_x_nuspecs_inputmask_nuspec.sql
@@application/shared_components/files/inputmask_4_x_nuspecs_readme_txt.sql
@@application/shared_components/files/inputmask_4_x_nuspecs_jquery_inputmask_nuspec.sql
@@application/shared_components/files/inputmask_4_x_package_json.sql
@@application/shared_components/files/inputmask_4_x_qunit_index_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_prototypeextensions_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_qunit_html.sql
@@application/shared_components/files/inputmask_4_x_qunit_simulator_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_alternations_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_attributes_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_base_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_date_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_dynamic_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_escape_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_formatvalidate_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_initialvalue_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_inputeventonly_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_ip_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_jitmasking_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_jquery_inputmask_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_keepstatic_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_multi_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_numeric_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_numericinput_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_option_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_optional_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_paste_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_regex_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_tests_setvalue_js.sql
@@application/shared_components/files/inputmask_4_x_qunit_webpack_config_js.sql
@@application/shared_components/files/inputmask_4_x_webpack_config_js.sql
@@application/shared_components/files/inputmask_4_x_webpackbuild_config_js.sql
@@application/shared_components/files/autonumeric_js.sql
@@application/shared_components/files/app_136_logo_png.sql
@@application/shared_components/files/app_138_logo_png.sql
@@application/shared_components/files/logo200_png.sql
@@application/shared_components/files/audl0007_docx.sql
@@application/shared_components/files/audl0006_docx.sql
@@application/shared_components/files/audl0005_docx.sql
@@application/shared_components/files/audl0004_docx.sql
@@application/shared_components/files/prueba_docx.sql
@@application/shared_components/files/fondo_menu2_jpg.sql
@@application/shared_components/files/fondo_menu_imgid1_png.sql
@@application/shared_components/files/fondo_menu_1_svg.sql
@@application/shared_components/files/fondo_menu_jpg.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/permiso_actualizar.sql
@@application/shared_components/security/authorizations/permiso_borrar.sql
@@application/shared_components/security/authorizations/permiso_crear.sql
@@application/shared_components/security/authorizations/acceso_pagina.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/obtener_legajo.sql
@@application/shared_components/logic/application_processes/obtener_sucursal.sql
@@application/shared_components/logic/application_processes/obtener_roles.sql
@@application/shared_components/logic/application_processes/set_report_url.sql
@@application/shared_components/logic/application_items/app_name.sql
@@application/shared_components/logic/application_items/legajo.sql
@@application/shared_components/logic/application_items/menu_permisos.sql
@@application/shared_components/logic/application_items/report_base_url.sql
@@application/shared_components/logic/application_items/report_format.sql
@@application/shared_components/logic/application_items/report_pass.sql
@@application/shared_components/logic/application_items/report_user.sql
@@application/shared_components/logic/application_items/roles.sql
@@application/shared_components/logic/application_items/sucursal.sql
@@application/shared_components/logic/application_items/v_dia1.sql
@@application/shared_components/logic/application_computations/menu_permisos.sql
@@application/shared_components/logic/application_computations/app_name.sql
@@application/shared_components/logic/application_computations/report_base_url.sql
@@application/shared_components/logic/application_computations/report_user.sql
@@application/shared_components/logic/application_computations/report_pass.sql
@@application/shared_components/logic/application_computations/report_format.sql
@@application/shared_components/logic/application_computations/po_fecha_1.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/lov_caja_chica_descripcion.sql
@@application/shared_components/user_interface/lovs/lov_caja_chica_estado.sql
@@application/shared_components/user_interface/lovs/lov_centro_costos.sql
@@application/shared_components/user_interface/lovs/lov_colaboradores.sql
@@application/shared_components/user_interface/lovs/lov_colas_gdd_listar.sql
@@application/shared_components/user_interface/lovs/lov_datos_tipos.sql
@@application/shared_components/user_interface/lovs/lov_domain_planilla.sql
@@application/shared_components/user_interface/lovs/lov_ejercicio_destino.sql
@@application/shared_components/user_interface/lovs/lov_ejercicio_origen.sql
@@application/shared_components/user_interface/lovs/lov_empresas.sql
@@application/shared_components/user_interface/lovs/lov_entidad_dato_sucursal.sql
@@application/shared_components/user_interface/lovs/lov_estado.sql
@@application/shared_components/user_interface/lovs/lov_estados_gdd.sql
@@application/shared_components/user_interface/lovs/lov_estado_gasto_cc.sql
@@application/shared_components/user_interface/lovs/lov_estado_rendiciones.sql
@@application/shared_components/user_interface/lovs/lov_gastos_estados.sql
@@application/shared_components/user_interface/lovs/lov_gastos_facturas.sql
@@application/shared_components/user_interface/lovs/lov_gastos_impuestos.sql
@@application/shared_components/user_interface/lovs/lov_gastos_rubros.sql
@@application/shared_components/user_interface/lovs/lov_legajos.sql
@@application/shared_components/user_interface/lovs/lov_legajos_audl0003.sql
@@application/shared_components/user_interface/lovs/lov_legajo_reportes.sql
@@application/shared_components/user_interface/lovs/lov_monedas.sql
@@application/shared_components/user_interface/lovs/lov_prioridades.sql
@@application/shared_components/user_interface/lovs/lov_programas.sql
@@application/shared_components/user_interface/lovs/lov_programas_auda0004.sql
@@application/shared_components/user_interface/lovs/lov_programas_ejercicios.sql
@@application/shared_components/user_interface/lovs/lov_programas_padre.sql
@@application/shared_components/user_interface/lovs/lov_ramos_proveedores.sql
@@application/shared_components/user_interface/lovs/lov_tareas.sql
@@application/shared_components/user_interface/lovs/lov_tareas_prueba.sql
@@application/shared_components/user_interface/lovs/lov_tipo_factura.sql
@@application/shared_components/user_interface/lovs/lov_tipo_impuesto.sql
@@application/shared_components/user_interface/lovs/lov_tipo_rubro.sql
@@application/shared_components/user_interface/lovs/lov_ubicaciones.sql
@@application/shared_components/user_interface/lovs/lov_vales_estado.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/template_coomecipar.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/login_background.sql
@@application/shared_components/user_interface/templates/button/coomecipar_ltda_button.sql
@@application/shared_components/user_interface/templates/button/coomecipar_ltda_button_plus.sql
@@application/shared_components/user_interface/templates/button/coomecipar_ltda_button_primary.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text_with_icon_left.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/cooperativa_ltda_standard.sql
@@application/shared_components/user_interface/templates/region/login_coo.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/login_coomecipar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/optional_coomecipar.sql
@@application/shared_components/user_interface/templates/label/optional_excelsis.sql
@@application/shared_components/user_interface/templates/label/prueba_hector.sql
@@application/shared_components/user_interface/templates/label/optional_coomecipar_ltda.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/database_accounts.sql
@@application/shared_components/plugins/dynamic_action/com_fos_interactive_grid_add_button.sql
@@application/shared_components/plugins/dynamic_action/de_danielh_toastrnotifications.sql
@@application/shared_components/plugins/region_type/de_danielh_dropzone2.sql
@@application/shared_components/plugins/dynamic_action/com_fos_interactive_grid_process_rows.sql
@@application/shared_components/plugins/process_type/be_apexrnd_aop.sql
@@application/shared_components/plugins/dynamic_action/com_apexutils_execute_plsql_code.sql
@@application/shared_components/plugins/dynamic_action/be_apexrnd_aop_da.sql
@@application/shared_components/plugins/dynamic_action/be_apexrnd_aop_convert_da.sql
@@application/shared_components/plugins/dynamic_action/com_aaw_loadingicon.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00007.sql
@@application/pages/page_09999.sql
@@application/end_environment.sql
